"use strict";
const $ = (selector) => document.querySelector(selector);
const groups = {regression:["1.12.2","1.13.2","1.21.11","26.2"],legacy:["1.9","1.10.2","1.11.2","1.12.2"],modern:["1.16.5","1.18.2","1.20.6","26.2"]};
const views = {all:["Deine Testserver.","Alle Server","Wähle eine Version oder stelle dir eine Testgruppe zusammen."],running:["Bereit zum Testen.","Laufende Server","Diese Welten sind gerade erreichbar oder werden gestartet."],favorites:["Deine Favoriten.","Favoriten","Deine häufig getesteten Versionen, mit einem Stern gespeichert."],regression:["Die wichtigsten Checks.","Regression","1.12.2 · 1.13.2 · 1.21.11 · 26.2 — vier Stationen für deine bisherigen Fehlerfälle."],legacy:["Zurück zu den Anfängen.","Legacy","1.9 · 1.10.2 · 1.11.2 · 1.12.2 — klassische IDs und Metadaten testen."],modern:["Neuere Welten erkunden.","Modern","1.16.5 · 1.18.2 · 1.20.6 · 26.2 — neue Formate und Inhalte vergleichen."]};
let state = {servers:[],jobs:[],token:null}, view = "all", selected = new Set(), favorites = new Set();
let activeVersion = null, activeTab = "overview", catalog = [], catalogLimit = 100, catalogError = null;
let terminating = false, shutdownDone = false;
let polling = false, connected = false, submitting = false, toastTimer, tableSignature = "", activitySignature = "";
try { favorites = new Set(JSON.parse(localStorage.getItem("viaforge.favorites") || "[]")); } catch (_) {}
const esc = (value) => String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const number = (value) => Number(value).toLocaleString("de-DE");
const gb = (value) => (value / 1024).toLocaleString("de-DE",{maximumFractionDigits:1});
const cube = '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9L12 3Z" stroke="currentColor" stroke-width="1.3"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9M8 5.3l8 4.5" stroke="currentColor" stroke-width="1.3"/></svg>';
function toast(message,error=false){const el=$("#toast");el.textContent=message;el.classList.toggle("error",error);el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,error?7000:3500);}
async function copy(value){try{await navigator.clipboard.writeText(value);toast("Kopiert: "+value);}catch(_){toast("Kopieren nicht möglich. Adresse oder Befehl bitte manuell markieren.",true);}}
function jobFor(version){return state.jobs.find(j=>j.versions.includes(version)&&["queued","running"].includes(j.state));}
function statusOf(row){const job=jobFor(row.version);if(job)return {label:job.state==="queued"?"Wartet":({start:"Startet …",stop:"Speichert …",verify:"Prüft …",inspect:"Prüft …",restore:"Wiederherstellung",kit:"Testpaket …",op:"Operator …"}[job.action]),kind:"busy"};return ({running:{label:"Online",kind:"running"},starting:{label:"Startet …",kind:"busy"},conflict:{label:"Port belegt",kind:"conflict"},offline:{label:"Offline",kind:"offline"}})[row.state];}
function canStart(row){return connected&&!submitting&&!terminating&&row.prepared&&!jobFor(row.version)&&row.state==="offline";}
function canStop(row){return connected&&!submitting&&!terminating&&row.managed&&!jobFor(row.version)&&row.state==="running";}
function visibleRows(){let rows=state.servers.filter(r=>view==="all"||(view==="running"&&["running","starting"].includes(r.state))||(view==="favorites"&&favorites.has(r.version))||(groups[view]||[]).includes(r.version));const query=$("#search").value.toLowerCase().trim(),filter=$("#status-filter").value;rows=rows.filter(r=>(r.version+" "+r.address+" "+r.protocol).includes(query)&&(filter==="all"||statusOf(r).kind===filter));const sort=$("#sort").value;return rows.sort((a,b)=>sort==="oldest"?a.protocol-b.protocol:sort==="online"?(Number(b.state==="running")-Number(a.state==="running")||b.protocol-a.protocol):b.protocol-a.protocol);}
function setView(next){view=next;$("#search").value="";$("#status-filter").value="all";document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===view));$("#page-title").textContent=views[view][0];$("#group-description").textContent=views[view][2];$("#quick-start").innerHTML="<span>▶</span> "+(groups[view]?views[view][1]:"Regression")+" starten";render();}
function render(){
  renderShutdown();
  const online=state.servers.filter(r=>r.state==="running"),checked=state.servers.filter(r=>r.verified===true),players=online.reduce((n,r)=>n+r.players,0);
  $("#nav-running").textContent=state.updated_at?online.length:"–";$("#nav-favorites").textContent=favorites.size;
  $("#metric-online").innerHTML=(state.updated_at?online.length:"–")+"<small>Server</small>";
  $("#metric-players").textContent=state.updated_at?players+" Spieler verbunden":"Status wird geladen …";
  $("#metric-memory").innerHTML=(state.free_mb!=null?gb(state.free_mb):"–")+"<small>GB</small>";
  $("#metric-worlds").innerHTML=(state.updated_at?checked.length:"–")+"<small>/ 48</small>";
  $("#metric-checks").textContent=state.updated_at?number(checked.reduce((n,r)=>n+r.checks,0))+" erfolgreiche Einzelprüfungen":"Letzte gespeicherte Prüfergebnisse";
  $("#quick-start").disabled=!connected||submitting||!(groups[view]||groups.regression).some(v=>canStart(state.servers.find(r=>r.version===v)||{}));
  const rows=visibleRows();$("#list-title").innerHTML=esc(views[view][1])+" <span>"+rows.length+"</span>";
  $("#table-count").textContent=rows.length+" von 48 Versionen";
  const markup=rows.map(r=>{const s=statusOf(r),busy=jobFor(r.version);const action=canStop(r)?"stop":"start",enabled=action==="stop"?canStop(r):canStart(r);return `<tr class="${selected.has(r.version)?"selected":""}"><td class="check-cell"><input type="checkbox" data-select="${r.version}" aria-label="${r.version} auswählen" ${selected.has(r.version)?"checked":""}></td><td><div class="version-cell"><div class="version-icon ${r.protocol<=340?"legacy":r.protocol>=735?"new":""}">${cube}</div><div><button class="version-button" data-details="${r.version}">${r.version}</button><span class="version-sub">Vanilla · Protokoll ${r.protocol}</span></div></div></td><td><span class="status-pill ${s.kind}">${s.label}</span>${r.state==="running"?`<span class="status-sub">${r.players} Spieler${r.managed?"":" · extern gestartet"}</span>`:""}</td><td><button class="copy-address" data-copy="${r.address}" aria-label="Adresse ${r.version} kopieren">${r.address}</button></td><td><button class="world-link" data-catalog="${r.version}" ${r.catalog?"":"disabled"}>${number(r.blocks)} Blöcke · ${r.mobs} Mobs ↗</button><span class="world-sub">${r.exhibit_issues>0?r.exhibit_issues+" Exponate prüfen":r.verified===true?"✓ Welt geprüft":r.verified===false?"Prüfung fehlgeschlagen":r.prepared?"Welt vorbereitet":"Noch nicht eingerichtet"}</span></td><td class="align-right"><div class="row-actions"><button class="icon-button ${favorites.has(r.version)?"favorited":""}" data-favorite="${r.version}" aria-label="${r.version} als Favorit" aria-pressed="${favorites.has(r.version)}">${favorites.has(r.version)?"★":"☆"}</button><button class="button small ${action==="stop"?"stop":""}" data-action="${action}" data-version="${r.version}" ${enabled?"":"disabled"}>${busy?"In Arbeit":r.state==="running"?"■ Stoppen":"▶ Starten"}</button><button class="icon-button" data-details="${r.version}" aria-label="Details zu ${r.version}">›</button></div></td></tr>`;}).join("");
  if(markup!==tableSignature){$("#server-rows").innerHTML=markup;tableSignature=markup;}
  $("#empty").hidden=rows.length>0;
  if(!rows.length){$("#empty h3").textContent=state.updated_at?"Keine passenden Server":"Server werden geladen";$("#empty p").textContent=state.updated_at?(view==="favorites"?"Markiere deine Lieblingsversionen mit dem Stern.":view==="running"?"Starte eine Version aus der Übersicht oder eine Testgruppe.":"Passe die Suche oder den Statusfilter an."):"Die lokalen Versionen werden auf Erreichbarkeit geprüft.";}
  const chosen=state.servers.filter(r=>selected.has(r.version)),starts=chosen.filter(canStart),stops=chosen.filter(canStop);
  $("#selection-count").textContent=chosen.length?chosen.length+" ausgewählt":"Alle sichtbaren auswählen";
  $("#selection-memory").textContent=starts.length?"Startbedarf ca. "+gb(starts.reduce((n,r)=>n+r.budget_mb,0))+" GB":"";
  $("#select-all").checked=rows.length>0&&rows.every(r=>selected.has(r.version));$("#select-all").indeterminate=rows.some(r=>selected.has(r.version))&&!$("#select-all").checked;
  $("#start-selected").disabled=!starts.length;$("#stop-selected").disabled=!stops.length;$("#clear-selection").hidden=!chosen.length;
  renderActivities();if(activeVersion&&$("#detail-dialog").open)renderDetail();
}
function renderActivities(){const labels={queued:"Wartet",running:"Läuft",success:"Fertig",failed:"Fehlgeschlagen"};const jobs=state.jobs.slice().reverse().slice(0,8);const markup=jobs.map(j=>`<details class="activity" data-job="${j.id}"><summary><span class="activity-dot ${j.state}"></span><strong>${esc(j.title)}</strong><span class="activity-versions">${esc(j.versions.join(", "))}</span><span class="quiet">${labels[j.state]}</span><time>${new Date(j.created*1000).toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit"})}</time></summary><pre>${esc(j.output|| (j.state==="queued"?"Die Aktion beginnt nach dem vorherigen Auftrag.":"Aktion läuft. Der Server benötigt einen Moment …"))}</pre></details>`).join("")||'<p class="quiet">Noch keine Aktionen. Deine Server warten auf den nächsten Test.</p>';if(markup!==activitySignature){const open=new Set([...document.querySelectorAll(".activity[open]")].map(e=>e.dataset.job));$("#activities").innerHTML=markup;document.querySelectorAll(".activity").forEach(el=>el.open=open.has(el.dataset.job)||jobs.find(j=>j.id===el.dataset.job)?.state==="failed");activitySignature=markup;}}
async function poll(){if(polling||shutdownDone)return;polling=true;try{const response=await fetch("/api/state",{signal:AbortSignal.timeout(10000)});if(!response.ok)throw Error("Die lokale Verwaltung antwortet nicht.");state=await response.json();if(state.app!=="viaforge-testlabor-web-v1")throw Error("Unerwartete Antwort der Verwaltung.");connected=true;$("#connection").textContent=state.updated_at?"Live · "+new Date(state.updated_at*1000).toLocaleTimeString("de-DE"):"Server werden geprüft …";$("#connection").classList.remove("disconnected");$("#connection-error").hidden=!state.error;$("#connection-error").textContent=state.error?"Statusprüfung fehlgeschlagen: "+state.error:"";}catch(error){connected=false;$("#connection").textContent="Verbindung unterbrochen";$("#connection").classList.add("disconnected");$("#connection-error").hidden=false;$("#connection-error").textContent="Die Webverwaltung ist nicht erreichbar. Öffne Testserver.vbs erneut. Angezeigte Serverzustände sind möglicherweise veraltet.";}finally{polling=false;render();}if(terminating&&!shutdownDone)setTimeout(poll,400);if(activeVersion&&activeTab==="log"&&$("#detail-dialog").open)loadLog();}
async function submit(action,versions,player=""){if(!connected||terminating||!versions.length||submitting)return;submitting=true;render();try{const response=await fetch("/api/actions",{method:"POST",headers:{"Content-Type":"application/json","X-Lab-Token":state.token},body:JSON.stringify({action,versions,player}),signal:AbortSignal.timeout(10000)});const result=await response.json();if(!response.ok)throw Error(result.error||"Aktion fehlgeschlagen.");state.jobs.push(result);toast(result.title+": "+versions.join(", "));await poll();}catch(error){toast(error.message,true);}finally{submitting=false;render();}}
function chooseAction(action){submit(action,state.servers.filter(r=>selected.has(r.version)&&(action==="start"?canStart(r):canStop(r))).map(r=>r.version));}
function renderDetail(){const r=state.servers.find(r=>r.version===activeVersion);if(!r)return;const s=statusOf(r);$("#detail-title").textContent="Minecraft "+r.version;$("#detail-meta").innerHTML=`<span class="status-pill ${s.kind}">${s.label}</span><button class="copy-address" data-copy="${r.address}">${r.address}</button>`;
  $("#detail-overview").innerHTML=`<div class="detail-card detail-stats"><div><span>Blocktypen</span><strong>${number(r.blocks)}</strong></div><div><span>Itemstacks</span><strong>${number(r.items)}</strong></div><div><span>Mobtypen</span><strong>${r.mobs}</strong></div></div><div class="detail-card"><h3>Verbinden & loslegen</h3><p>Wähle in ViaForge <strong>${r.version}</strong> und verbinde dich mit <strong>${r.address}</strong>. Die Navigation erreichst du über den Knopf an der Ankunftsplattform.</p><div class="button-row"><button class="button primary" data-action="start" data-version="${r.version}" ${canStart(r)?"":"disabled"}>▶ Starten</button><button class="button" data-action="stop" data-version="${r.version}" ${canStop(r)?"":"disabled"}>■ Speichern & stoppen</button><button class="button" data-copy="${r.address}">Adresse kopieren</button></div><div class="test-locations"><div><span>Ankunftsplattform</span><button data-copy="/tp @p 0 177 0">0, 177, 0 ⧉</button></div><div><span>Teststationen & Navigation</span><button data-copy="/tp @p 0 65 -100">0, 65, −100 ⧉</button></div><div><span>Wasser & Boote</span><button data-copy="/tp @p 20 65 -95">20, 65, −95 ⧉</button></div></div></div>`;
  const enabled=canStop(r);$("#give-kit").disabled=!enabled;$("#give-op").disabled=!enabled;$("#verify-world").disabled=!enabled;$("#inspect-world").disabled=!connected||terminating||submitting||!!jobFor(r.version)||r.state!=="offline";$("#restore-world").disabled=$("#inspect-world").disabled;$("#restore-status").textContent=r.state!=="offline"?"Zuerst speichern und stoppen, dann wiederherstellen.":"Die Wiederherstellung dauert je nach Version einige Minuten.";$("#exhibit-status").textContent=(r.exhibit_issues!=null?(r.exhibit_issues? r.exhibit_issues+" abweichende Exponate gefunden.":"Letzter Exponatabgleich: keine unerwarteten Abweichungen."):"Noch kein Abgleich der gespeicherten Exponate.")+" Diese Prüfung ist bei beendetem Server verfügbar.";
}
async function showDetails(version,tab="overview"){activeVersion=version;catalog=[];catalogError=null;catalogLimit=100;$("#catalog-search").value="";$("#catalog-kind").value="all";renderDetail();if(!$("#detail-dialog").open)$("#detail-dialog").showModal();setTab(tab);}
function setTab(tab){activeTab=tab;document.querySelectorAll("[data-tab]").forEach(b=>b.setAttribute("aria-selected",b.dataset.tab===tab));for(const t of ["overview","catalog","log"])$("#pane-"+t).hidden=t!==tab;if(tab==="catalog")loadCatalog();if(tab==="log")loadLog();}
async function loadCatalog(){const version=activeVersion;$("#catalog-count").textContent="Katalog wird geladen …";try{const response=await fetch("/api/servers/"+version+"/catalog");const data=await response.json();if(!response.ok)throw Error(data.error);if(activeVersion!==version)return;catalog=["blocks","items","mobs","variants"].flatMap(kind=>(data[kind]||[]).map(x=>({...x,kind})));catalogError=null;renderCatalog();}catch(error){if(activeVersion===version){catalogError=error.message;renderCatalog();}}}
function renderCatalog(){const query=$("#catalog-search").value.trim().toLowerCase().replaceAll(" ","_"),kind=$("#catalog-kind").value,found=catalog.filter(x=>(kind==="all"||x.kind===kind)&&(x.name+" "+(x.variant||"")).toLowerCase().includes(query));$("#catalog-count").textContent=catalogError||number(found.length)+" Treffer · "+Math.min(found.length,catalogLimit)+" angezeigt";$("#catalog-results").innerHTML=found.slice(0,catalogLimit).map(x=>{const p=x.position||x.chest;const cmd=p?`/tp @p ${p[0]} ${p[1]+1} ${p[2]-2}`:"";return `<div class="catalog-entry"><div><strong>${esc(x.name.replace("minecraft:",""))}${x.variant?" · "+esc(x.variant):""}</strong><p>${({blocks:"Block",items:"Item",mobs:"Mob",variants:"Variante"})[x.kind]}${x.on_demand?" · auf Knopfdruck":""}${x.slot!==undefined?" · Kiste, Slot "+x.slot:""}${x.metadata?" · Meta "+x.metadata:""} · ${p?esc(p.join(", ")):"Kein Exponat"}</p></div>${p?`<button class="button small" data-copy="${esc(cmd)}" aria-label="Teleportbefehl für ${esc(x.name)} kopieren">/tp kopieren</button>`:""}</div>`;}).join("");$("#catalog-more").hidden=found.length<=catalogLimit;}
async function loadLog(){const version=activeVersion;try{const response=await fetch("/api/servers/"+version+"/log");const data=await response.json();if(activeVersion===version){const el=$("#server-log"),bottom=el.scrollHeight-el.scrollTop-el.clientHeight<45;el.textContent=data.output||"Noch keine Servermeldungen vorhanden.";if(bottom)el.scrollTop=el.scrollHeight;}}catch(_){if(activeVersion===version)$("#server-log").textContent="Protokoll konnte nicht geladen werden.";}}
document.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.view)setView(b.dataset.view);if(b.dataset.copy)copy(b.dataset.copy);if(b.dataset.details)showDetails(b.dataset.details);if(b.dataset.catalog)showDetails(b.dataset.catalog,"catalog");if(b.dataset.close)$("#"+b.dataset.close).close();if(b.dataset.tab)setTab(b.dataset.tab);if(b.dataset.action)submit(b.dataset.action,[b.dataset.version]);if(b.dataset.favorite){const v=b.dataset.favorite;favorites.has(v)?favorites.delete(v):favorites.add(v);try{localStorage.setItem("viaforge.favorites",JSON.stringify([...favorites]));}catch(_){}render();}});
$("#server-rows").addEventListener("change",e=>{if(e.target.dataset.select){const v=e.target.dataset.select;e.target.checked?selected.add(v):selected.delete(v);render();}});
$("#select-all").addEventListener("change",e=>{visibleRows().forEach(r=>e.target.checked?selected.add(r.version):selected.delete(r.version));render();});
$("#clear-selection").onclick=()=>{selected.clear();render();};$("#start-selected").onclick=()=>chooseAction("start");$("#stop-selected").onclick=()=>chooseAction("stop");
$("#quick-start").onclick=()=>submit("start",(groups[view]||groups.regression).filter(v=>canStart(state.servers.find(r=>r.version===v)||{})));
$("#search").oninput=render;$("#status-filter").onchange=render;$("#sort").onchange=render;$("#refresh").onclick=poll;$("#help-button").onclick=()=>$("#help-dialog").showModal();
$("#catalog-search").oninput=()=>{catalogLimit=100;renderCatalog();};$("#catalog-kind").onchange=()=>{catalogLimit=100;renderCatalog();};$("#catalog-more").onclick=()=>{catalogLimit+=100;renderCatalog();};
$("#give-kit").onclick=()=>submit("kit",[activeVersion],$("#player-name").value.trim());$("#give-op").onclick=()=>submit("op",[activeVersion],$("#player-name").value.trim());$("#verify-world").onclick=()=>submit("verify",[activeVersion]);$("#inspect-world").onclick=()=>submit("inspect",[activeVersion]);$("#restore-world").onclick=()=>submit("restore",[activeVersion]);
$("#detail-dialog").addEventListener("close",()=>{activeVersion=null;});
document.querySelectorAll("dialog").forEach(d=>d.addEventListener("click",e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
function renderShutdown(){
  const job=state.closing;
  terminating=!!job&&job.state!=="failed";
  $("#shutdown-button").disabled=!connected||shutdownDone;
  $("#shutdown-options").hidden=terminating;
  if(!job)return;
  if(job.state==="success"){
    shutdownDone=true;connected=false;
    $("#connection").textContent="Anwendung beendet";
    $("#connection-error").hidden=true;
    $("#shutdown-progress").textContent=job.mode==="all"?"Alle verwalteten Testserver wurden gespeichert und beendet. Die Webverwaltung ist beendet.":"Die Webverwaltung ist beendet. Deine Minecraft-Testserver laufen weiter.";
    if(job.mode==="all")state.servers.forEach(r=>{if(r.managed){r.state="offline";r.players=0;}});
  }else if(job.state==="failed"){
    $("#shutdown-progress").textContent="Das Beenden ist fehlgeschlagen. Die Verwaltung bleibt geöffnet. Details stehen unter Letzte Aktionen; du kannst es danach erneut versuchen.";
  }else{
    $("#shutdown-progress").textContent=job.state==="queued"?"Warte auf vorherige Aufträge …":job.mode==="all"?"Die Server werden gespeichert und beendet …":"Die Webverwaltung wird beendet …";
    if(!connected)$("#connection-error").textContent="Die Webverwaltung antwortet nach dem Beenden nicht mehr. Falls keine Abschlussmeldung erschien, öffne Testserver.vbs erneut, um den Serverstatus zu prüfen.";
  }
}
async function shutdown(mode){
  try{
    const response=await fetch("/api/shutdown",{method:"POST",headers:{"Content-Type":"application/json","X-Lab-Token":state.token},body:JSON.stringify({mode}),signal:AbortSignal.timeout(10000)});
    const job=await response.json();if(!response.ok)throw Error(job.error);
    state.closing=job;render();setTimeout(poll,200);
  }catch(error){toast(error.message,true);}
}
$("#shutdown-button").onclick=()=>$("#shutdown-dialog").showModal();
$("#shutdown-all").onclick=()=>shutdown("all");
$("#shutdown-web").onclick=()=>shutdown("web");
poll();setInterval(poll,5000);
