package com.viaversion.viaforge.common.compatibility;

/** Named behavior changes. Later profiles inherit these and may override them. */
public enum ClientRule {
    CRYSTAL_BEAM_OFFSET, EXTENDED_GATEWAY_BEAM, INTERPOLATED_GATEWAY_COOLDOWN,
    UPDATED_DYE_COLORS, REVERSED_DRAGON_HEAD_ITEM, MODERN_ATTACK_ICON,
    MERGED_MATERIALS_TAB, COMBAT_CURSE_BOOKS, NAMESPACED_ENTITY_IDS,
    FAST_PADDLE_CYCLE, EXCLUSIVE_TURN_PADDLES, COLORED_SHULKERS, UPDATED_ILLAGER_ARMS,
    SMALL_VEX_MODEL, INDIVIDUAL_EGG_MODELS, BIOME_WATER_COLORS, PREDICT_HOTBAR_DROPS, ELYTRA_FIREWORKS,
    FIREWORK_HAND_TRAIL, TICKED_ELYTRA_WINGS, ROCKET_USE_SWING, SHIELD_FOLLOWS_LOOK,
    SERVER_OWNS_USE_SWING, BOUNDED_INVENTORY_PREVIEW, CAPTURED_INVENTORY_FLIGHT,
    LIMITED_INVENTORY_FLIGHT_YAW, CRAWLING_POSE, PREDICT_ELYTRA_START, FIXED_CRAWLING_HEAD,
    SMALL_MOTION_THRESHOLD, HORIZONTAL_MOTION_THRESHOLD, EARLY_POSITION_REMINDER,
    ROTATION_ONLY_ENTITY_UPDATE, KEEP_ZERO_ENTITY_DELTA, ROUND_ENTITY_DELTA,
    CLIENT_ENTITY_PUSH, SLEEPING_PUSH_IMMUNITY, PRECISE_ENTITY_PUSH, PUSHABLE_IMPULSE_TARGETS,
    SWIMMING, DOUBLE_SWIM_INPUT, DELAYED_WATER_EYES, MINIMUM_FLUID_CURRENT, SWIM_FEET_IN_WATER,
    ENTITY_FLUID_TRACKER, PRECISE_MOVEMENT_PACKETS, SQUARE_SWIM_INPUT, DEFERRED_BLOCK_EFFECTS, CURRENT_AIR_SPRINT,
    SHIFT_SWIM_INPUT, WATER_EFFICIENCY_ATTRIBUTE, SWIFT_SNEAK, SNEAK_SPEED_ATTRIBUTE,
    MODERN_THIN_COLLISIONS, JUMP_CLIMBING, COMPONENT_BLOCKING, MODERN_BLOCK_USE_FAILURE
}
